export const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

export const initvaleur = () => {
  const initValeur = [
    {
      id: 1,
      date: '2022-04-16',
      nom: 'Trail de Matour',
      distance: '11.81',
      denivele: '385',
      temps: '1:01:52',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 2,
      date: '2021-09-12',
      nom: "Trail de la carrière d'Igé",
      distance: '13.58',
      denivele: '604',
      temps: '1:19:35',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 3,
      date: '2023-03-19',
      nom: 'Trail du Mont-Saint-Romain',
      distance: '16.68',
      denivele: '492',
      temps: '1:28:18',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 4,
      date: '2022-05-15',
      nom: 'La chatelaine',
      distance: '13.27',
      denivele: '342',
      temps: '1:08:55',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 5,
      date: '2022-05-01',
      nom: "Trail de la carrière d'Igé",
      distance: '14.06',
      denivele: '546',
      temps: '1:20:53',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 6,
      date: '2022-11-05',
      nom: "Trail des Grottes d'Azé",
      distance: '23.76',
      denivele: '763',
      temps: '2:14:33',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 7,
      date: '2022-03-20',
      nom: 'Trail du Mont-Saint-Romain',
      distance: '16.66',
      denivele: '496',
      temps: '1:32:31',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 8,
      date: '2023-09-10',
      nom: 'Trail de Matour',
      distance: '10.97',
      denivele: '370',
      temps: '1:02:54',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 9,
      date: '2020-09-13',
      nom: "Trail de la carrière d'Igé",
      distance: '13.16',
      denivele: '555',
      temps: '1:20:34',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 10,
      date: '2019-10-06',
      nom: 'Route des crus',
      distance: '12.68',
      denivele: '244',
      temps: '1:05:39',
      technicite: '1',
      conditionDifficile: false,
    },
    {
      id: 11,
      date: '2019-04-07',
      nom: "L'escrapade",
      distance: '18.49',
      denivele: '588',
      temps: '1:46:18',
      technicite: '1',
      conditionDifficile: false,
    },
  ]

  localStorage.setItem('resultats', JSON.stringify(initValeur))
}
