export const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

export const initvaleur = () => {
  const initValeur = [
    {
      id: 1,
      date: '2022-04-16',
      nom: 'Trail de Matour',
      distance: '11.81',
      denivele: '385',
      temps: '1:01:52',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 2,
      date: '2021-09-12',
      nom: "Trail de la carrière d'Igé",
      distance: '13.58',
      denivele: '604',
      temps: '1:19:35',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 3,
      date: '2023-03-19',
      nom: 'Trail du Mont-Saint-Romain',
      distance: '16.68',
      denivele: '492',
      temps: '1:28:18',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 4,
      date: '2022-05-15',
      nom: 'La chatelaine',
      distance: '13.27',
      denivele: '342',
      temps: '1:08:55',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 5,
      date: '2022-05-01',
      nom: "Trail de la carrière d'Igé",
      distance: '14.06',
      denivele: '546',
      temps: '1:20:53',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 6,
      date: '2022-11-05',
      nom: "Trail des Grottes d'Azé",
      distance: '23.76',
      denivele: '763',
      temps: '2:14:33',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 7,
      date: '2022-03-20',
      nom: 'Trail du Mont-Saint-Romain',
      distance: '16.66',
      denivele: '496',
      temps: '1:32:31',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 8,
      date: '2023-09-10',
      nom: 'Trail de Matour',
      distance: '10.97',
      denivele: '370',
      temps: '1:02:54',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 9,
      date: '2020-09-13',
      nom: "Trail de la carrière d'Igé",
      distance: '13.16',
      denivele: '555',
      temps: '1:20:34',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 10,
      date: '2019-10-06',
      nom: 'Route des crus',
      distance: '12.68',
      denivele: '244',
      temps: '1:05:39',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 11,
      date: '2019-04-07',
      nom: "L'escrapade",
      distance: '18.49',
      denivele: '588',
      temps: '1:46:18',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 12,
      date: '2019-06-22',
      nom: 'XT01',
      distance: '16.5',
      denivele: '562',
      temps: '1:38:39',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 13,
      date: '2022-10-29',
      nom: 'Cavale des 3 Monts',
      distance: '19.8',
      denivele: '589',
      temps: '1:55:20',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 14,
      date: '2024-10-06',
      nom: 'Trail du Mâconnais',
      distance: '18.66',
      denivele: '601',
      temps: '1:51:30',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 15,
      date: '2022-10-22',
      nom: 'Trail du Haut Clunysois',
      distance: '18.96',
      denivele: '744',
      temps: '1:59:29',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 16,
      date: '2019-09-01',
      nom: 'Ronde des grangeons',
      distance: '16.59',
      denivele: '474',
      temps: '1:37:54',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 17,
      date: '2019-05-19',
      nom: 'La chatelaine',
      distance: '29.93',
      denivele: '1011',
      temps: '3:03:47',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 18,
      date: '2023-01-15',
      nom: "Trail d'Avenas",
      distance: '18.75',
      denivele: '1092',
      temps: '2:17:52',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 19,
      date: '2022-06-18',
      nom: 'ULTRA01',
      distance: '24.05',
      denivele: '779',
      temps: '2:30:03',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 20,
      date: '2020-01-19',
      nom: "Trail d'Avenas",
      distance: '20.31',
      denivele: '745',
      temps: '2:11:34',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 21,
      date: '2022-02-19',
      nom: 'Trace des maquisards',
      distance: '16.12',
      denivele: '717',
      temps: '1:50:46',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 22,
      date: '2019-03-03',
      nom: 'Trail de Mouge',
      distance: '20.86',
      denivele: '467',
      temps: '2:02:48',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 23,
      date: '2019-10-26',
      nom: 'Izernight',
      distance: '23.19',
      denivele: '852',
      temps: '2:36:56',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 24,
      date: '2024-09-22',
      nom: 'Tour des crus / duo',
      distance: '25.03',
      denivele: '910',
      temps: '2:49:54',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: true,
    },
    {
      id: 25,
      date: '2021-06-27',
      nom: 'Trail des 2 Roches',
      distance: '26.67',
      denivele: '1161',
      temps: '3:12:48',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 26,
      date: '2024-03-17',
      nom: 'Trail du Mont-Saint-Romain',
      distance: '44.91',
      denivele: '1531',
      temps: '5:11:37',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 27,
      date: '2022-09-03',
      nom: 'Trail de la Planete',
      distance: '28.38',
      denivele: '1018',
      temps: '3:19:12',
      technicite: '2',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 28,
      date: '2019-03-17',
      nom: 'Trail du Mont-Saint-Romain',
      distance: '30.23',
      denivele: '919',
      temps: '3:24:19',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 29,
      date: '2020-09-06',
      nom: 'Ronde des ramequins',
      distance: '25.92',
      denivele: '1351',
      temps: '3:26:35',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 30,
      date: '2019-10-12',
      nom: 'UTBV',
      distance: '26.37',
      denivele: '1125',
      temps: '3:18:05',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 31,
      date: '2024-04-27',
      nom: 'Saint Ju Trail',
      distance: '37.82',
      denivele: '1989',
      temps: '5:05:28',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 32,
      date: '2023-02-18',
      nom: 'Trace des maquisards',
      distance: '27.62',
      denivele: '1192',
      temps: '3:33:57',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 33,
      date: '2020-09-27',
      nom: 'Saint So Course',
      distance: '35.59',
      denivele: '1823',
      temps: '4:51:59',
      technicite: '2',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 34,
      date: '2020-09-19',
      nom: "Gi j'y monte",
      distance: '15.49',
      denivele: '614',
      temps: '1:57:26',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 35,
      date: '2019-02-03',
      nom: 'Trail Givré',
      distance: '22.49',
      denivele: '392',
      temps: '2:23:34',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 36,
      date: '2022-05-21',
      nom: 'UBVT',
      distance: '38.51',
      denivele: '1889',
      temps: '5:12:24',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 37,
      date: '2022-03-13',
      nom: 'Trail du Ventoux',
      distance: '47.22',
      denivele: '2568',
      temps: '6:45:44',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 38,
      date: '2023-10-07',
      nom: 'UTBV',
      distance: '41.78',
      denivele: '1920',
      temps: '5:41:17',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 39,
      date: '2025-03-09',
      nom: 'Trail du Ventoux',
      distance: '48.06',
      denivele: '2724',
      temps: '7:13:13',
      technicite: '2',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 40,
      date: '2021-10-09',
      nom: 'UTBV',
      distance: '53.07',
      denivele: '2398',
      temps: '7:27:32',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 41,
      date: '2019-09-28',
      nom: 'VLP',
      distance: '35.86',
      denivele: '1295',
      temps: '4:47:07',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 42,
      date: '2021-06-06',
      nom: 'Trail du Ventoux',
      distance: '44.93',
      denivele: '2336',
      temps: '6:48:32',
      technicite: '2',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 43,
      date: '2023-07-29',
      nom: '6000D Marathon',
      distance: '43.14',
      denivele: '2019',
      temps: '6:32:08',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 44,
      date: '2019-12-01',
      nom: 'SaintéLyon - relai 2',
      distance: '45.22',
      denivele: '1027',
      temps: '5:54:10',
      technicite: '1',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 45,
      date: '2020-03-08',
      nom: 'Trail du Ventoux',
      distance: '45.3',
      denivele: '2228',
      temps: '7:15:12',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 46,
      date: '2023-03-11',
      nom: 'Trail du Ventoux',
      distance: '73.62',
      denivele: '3863',
      temps: '12:22:59',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 47,
      date: '2021-11-27',
      nom: 'SaintéLyon',
      distance: '78.13',
      denivele: '2231',
      temps: '11:09:11',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 48,
      date: '2022-10-01',
      nom: 'UTMJ - Renarde',
      distance: '78.95',
      denivele: '3054',
      temps: '12:17:02',
      technicite: '1',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 49,
      date: '2022-06-26',
      nom: 'Marathon du Mont-Blanc',
      distance: '43.55',
      denivele: '2341',
      temps: '8:13:38',
      technicite: '3',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 50,
      date: '2025-10-11',
      nom: "Grand Trail d'Auvergne",
      distance: '130.87',
      denivele: '5161',
      temps: '23:07:27',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 51,
      date: '2023-06-10',
      nom: 'ULTRA01',
      distance: '89.98',
      denivele: '3659',
      temps: '16:04:40',
      technicite: '2',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 52,
      date: '2022-08-20',
      nom: 'Trail Galibier / Thabor (1/2)',
      distance: '36.73',
      denivele: '2586',
      temps: '7:57:51',
      technicite: '3',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 53,
      date: '2022-08-21',
      nom: 'Trail Galibier / Thabor (2/2)',
      distance: '31.16',
      denivele: '1148',
      temps: '5:30:09',
      technicite: '3',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 54,
      date: '2025-07-05',
      nom: 'Ultra Trail des 2 Roches',
      distance: '83.18',
      denivele: '3147',
      temps: '14:54:58',
      technicite: '2',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 55,
      date: '2021-08-21',
      nom: 'Trail Galibier / Thabor (1/2)',
      distance: '36.92',
      denivele: '2508',
      temps: '8:23:07',
      technicite: '3',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 56,
      date: '2021-08-22',
      nom: 'Trail Galibier / Thabor (2/2)',
      distance: '33.43',
      denivele: '1187',
      temps: '6:28:11',
      technicite: '3',
      conditionDifficile: false,
      horsCalcul: false,
    },
    {
      id: 57,
      date: '2024-06-14',
      nom: 'ULTRA01',
      distance: '170',
      denivele: '8500',
      temps: '43:54:55',
      technicite: '2',
      conditionDifficile: true,
      horsCalcul: false,
    },
    {
      id: 58,
      date: '2025-06-07',
      nom: "Trans'Ju trail",
      distance: '43',
      denivele: '2280',
      temps: '7:22:01',
      technicite: '1',
      conditionDifficile: true,
      horsCalcul: false,
    },
  ]

  localStorage.setItem('resultats', JSON.stringify(initValeur))
}
